# tflint configuration - tier 04 (large multi-team repo = strict ruleset).
#
# This repo checks in almost no *.tf (backend/provider blocks are generated by
# Terragrunt into the cache at run time), so tflint mostly matters for the
# module registry repo and for any component that starts vendoring .tf. It is
# wired into pre-commit (terraform_tflint) and can be run manually from any
# directory containing .tf files:
#
#   tflint --config=$(git rev-parse --show-toplevel)/.tflint.hcl
#
# Tier 4 enables the strict rules on top of the defaults:
#   terraform_comment_header      - every block deserves a comment header;
#                                   forces readable code across many teams.
#   terraform_unused_declarations - dead declarations rot multi-team repos;
#                                   keep them out.

plugin "terraform" {
  enabled = true
}

rule "terraform_comment_header" {
  enabled = true
}

rule "terraform_unused_declarations" {
  enabled = true
}
